server:
  port: 1000

messaging:
  broker: rabbitmq   # rabbitmq | ibmmq
  queue: test.queue

spring:
  application:
    name: messaging-service
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest




